# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tupi/Documents/code/bomberman_sdl2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tupi/Documents/code/bomberman_sdl2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tupi/Documents/code/bomberman_sdl2/CMakeFiles /home/tupi/Documents/code/bomberman_sdl2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tupi/Documents/code/bomberman_sdl2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bomberman

# Build rule for target.
bomberman: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bomberman
.PHONY : bomberman

# fast build rule for target.
bomberman/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/build
.PHONY : bomberman/fast

Animation.o: Animation.cpp.o
.PHONY : Animation.o

# target to build an object file
Animation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Animation.cpp.o
.PHONY : Animation.cpp.o

Animation.i: Animation.cpp.i
.PHONY : Animation.i

# target to preprocess a source file
Animation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Animation.cpp.i
.PHONY : Animation.cpp.i

Animation.s: Animation.cpp.s
.PHONY : Animation.s

# target to generate assembly for a file
Animation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Animation.cpp.s
.PHONY : Animation.cpp.s

app.o: app.cpp.o
.PHONY : app.o

# target to build an object file
app.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/app.cpp.o
.PHONY : app.cpp.o

app.i: app.cpp.i
.PHONY : app.i

# target to preprocess a source file
app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/app.cpp.i
.PHONY : app.cpp.i

app.s: app.cpp.s
.PHONY : app.s

# target to generate assembly for a file
app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/app.cpp.s
.PHONY : app.cpp.s

entities/Enemy.o: entities/Enemy.cpp.o
.PHONY : entities/Enemy.o

# target to build an object file
entities/Enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/entities/Enemy.cpp.o
.PHONY : entities/Enemy.cpp.o

entities/Enemy.i: entities/Enemy.cpp.i
.PHONY : entities/Enemy.i

# target to preprocess a source file
entities/Enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/entities/Enemy.cpp.i
.PHONY : entities/Enemy.cpp.i

entities/Enemy.s: entities/Enemy.cpp.s
.PHONY : entities/Enemy.s

# target to generate assembly for a file
entities/Enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/entities/Enemy.cpp.s
.PHONY : entities/Enemy.cpp.s

entities/MovingEntities.o: entities/MovingEntities.cpp.o
.PHONY : entities/MovingEntities.o

# target to build an object file
entities/MovingEntities.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/entities/MovingEntities.cpp.o
.PHONY : entities/MovingEntities.cpp.o

entities/MovingEntities.i: entities/MovingEntities.cpp.i
.PHONY : entities/MovingEntities.i

# target to preprocess a source file
entities/MovingEntities.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/entities/MovingEntities.cpp.i
.PHONY : entities/MovingEntities.cpp.i

entities/MovingEntities.s: entities/MovingEntities.cpp.s
.PHONY : entities/MovingEntities.s

# target to generate assembly for a file
entities/MovingEntities.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/entities/MovingEntities.cpp.s
.PHONY : entities/MovingEntities.cpp.s

entities/Object.o: entities/Object.cpp.o
.PHONY : entities/Object.o

# target to build an object file
entities/Object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/entities/Object.cpp.o
.PHONY : entities/Object.cpp.o

entities/Object.i: entities/Object.cpp.i
.PHONY : entities/Object.i

# target to preprocess a source file
entities/Object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/entities/Object.cpp.i
.PHONY : entities/Object.cpp.i

entities/Object.s: entities/Object.cpp.s
.PHONY : entities/Object.s

# target to generate assembly for a file
entities/Object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/entities/Object.cpp.s
.PHONY : entities/Object.cpp.s

entities/Player.o: entities/Player.cpp.o
.PHONY : entities/Player.o

# target to build an object file
entities/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/entities/Player.cpp.o
.PHONY : entities/Player.cpp.o

entities/Player.i: entities/Player.cpp.i
.PHONY : entities/Player.i

# target to preprocess a source file
entities/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/entities/Player.cpp.i
.PHONY : entities/Player.cpp.i

entities/Player.s: entities/Player.cpp.s
.PHONY : entities/Player.s

# target to generate assembly for a file
entities/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/entities/Player.cpp.s
.PHONY : entities/Player.cpp.s

entities/Sprite.o: entities/Sprite.cpp.o
.PHONY : entities/Sprite.o

# target to build an object file
entities/Sprite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/entities/Sprite.cpp.o
.PHONY : entities/Sprite.cpp.o

entities/Sprite.i: entities/Sprite.cpp.i
.PHONY : entities/Sprite.i

# target to preprocess a source file
entities/Sprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/entities/Sprite.cpp.i
.PHONY : entities/Sprite.cpp.i

entities/Sprite.s: entities/Sprite.cpp.s
.PHONY : entities/Sprite.s

# target to generate assembly for a file
entities/Sprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/entities/Sprite.cpp.s
.PHONY : entities/Sprite.cpp.s

entities/Text.o: entities/Text.cpp.o
.PHONY : entities/Text.o

# target to build an object file
entities/Text.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/entities/Text.cpp.o
.PHONY : entities/Text.cpp.o

entities/Text.i: entities/Text.cpp.i
.PHONY : entities/Text.i

# target to preprocess a source file
entities/Text.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/entities/Text.cpp.i
.PHONY : entities/Text.cpp.i

entities/Text.s: entities/Text.cpp.s
.PHONY : entities/Text.s

# target to generate assembly for a file
entities/Text.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/entities/Text.cpp.s
.PHONY : entities/Text.cpp.s

game.o: game.cpp.o
.PHONY : game.o

# target to build an object file
game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/game.cpp.o
.PHONY : game.cpp.o

game.i: game.cpp.i
.PHONY : game.i

# target to preprocess a source file
game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/game.cpp.i
.PHONY : game.cpp.i

game.s: game.cpp.s
.PHONY : game.s

# target to generate assembly for a file
game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/game.cpp.s
.PHONY : game.cpp.s

scenes/GameOverScene.o: scenes/GameOverScene.cpp.o
.PHONY : scenes/GameOverScene.o

# target to build an object file
scenes/GameOverScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/scenes/GameOverScene.cpp.o
.PHONY : scenes/GameOverScene.cpp.o

scenes/GameOverScene.i: scenes/GameOverScene.cpp.i
.PHONY : scenes/GameOverScene.i

# target to preprocess a source file
scenes/GameOverScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/scenes/GameOverScene.cpp.i
.PHONY : scenes/GameOverScene.cpp.i

scenes/GameOverScene.s: scenes/GameOverScene.cpp.s
.PHONY : scenes/GameOverScene.s

# target to generate assembly for a file
scenes/GameOverScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/scenes/GameOverScene.cpp.s
.PHONY : scenes/GameOverScene.cpp.s

scenes/GameScene.o: scenes/GameScene.cpp.o
.PHONY : scenes/GameScene.o

# target to build an object file
scenes/GameScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/scenes/GameScene.cpp.o
.PHONY : scenes/GameScene.cpp.o

scenes/GameScene.i: scenes/GameScene.cpp.i
.PHONY : scenes/GameScene.i

# target to preprocess a source file
scenes/GameScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/scenes/GameScene.cpp.i
.PHONY : scenes/GameScene.cpp.i

scenes/GameScene.s: scenes/GameScene.cpp.s
.PHONY : scenes/GameScene.s

# target to generate assembly for a file
scenes/GameScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/scenes/GameScene.cpp.s
.PHONY : scenes/GameScene.cpp.s

scenes/MenuScene.o: scenes/MenuScene.cpp.o
.PHONY : scenes/MenuScene.o

# target to build an object file
scenes/MenuScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/scenes/MenuScene.cpp.o
.PHONY : scenes/MenuScene.cpp.o

scenes/MenuScene.i: scenes/MenuScene.cpp.i
.PHONY : scenes/MenuScene.i

# target to preprocess a source file
scenes/MenuScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/scenes/MenuScene.cpp.i
.PHONY : scenes/MenuScene.cpp.i

scenes/MenuScene.s: scenes/MenuScene.cpp.s
.PHONY : scenes/MenuScene.s

# target to generate assembly for a file
scenes/MenuScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/scenes/MenuScene.cpp.s
.PHONY : scenes/MenuScene.cpp.s

scenes/Scene.o: scenes/Scene.cpp.o
.PHONY : scenes/Scene.o

# target to build an object file
scenes/Scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/scenes/Scene.cpp.o
.PHONY : scenes/Scene.cpp.o

scenes/Scene.i: scenes/Scene.cpp.i
.PHONY : scenes/Scene.i

# target to preprocess a source file
scenes/Scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/scenes/Scene.cpp.i
.PHONY : scenes/Scene.cpp.i

scenes/Scene.s: scenes/Scene.cpp.s
.PHONY : scenes/Scene.s

# target to generate assembly for a file
scenes/Scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/scenes/Scene.cpp.s
.PHONY : scenes/Scene.cpp.s

scenes/WinScene.o: scenes/WinScene.cpp.o
.PHONY : scenes/WinScene.o

# target to build an object file
scenes/WinScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/scenes/WinScene.cpp.o
.PHONY : scenes/WinScene.cpp.o

scenes/WinScene.i: scenes/WinScene.cpp.i
.PHONY : scenes/WinScene.i

# target to preprocess a source file
scenes/WinScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/scenes/WinScene.cpp.i
.PHONY : scenes/WinScene.cpp.i

scenes/WinScene.s: scenes/WinScene.cpp.s
.PHONY : scenes/WinScene.s

# target to generate assembly for a file
scenes/WinScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/scenes/WinScene.cpp.s
.PHONY : scenes/WinScene.cpp.s

scenes/textures.o: scenes/textures.cpp.o
.PHONY : scenes/textures.o

# target to build an object file
scenes/textures.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/scenes/textures.cpp.o
.PHONY : scenes/textures.cpp.o

scenes/textures.i: scenes/textures.cpp.i
.PHONY : scenes/textures.i

# target to preprocess a source file
scenes/textures.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/scenes/textures.cpp.i
.PHONY : scenes/textures.cpp.i

scenes/textures.s: scenes/textures.cpp.s
.PHONY : scenes/textures.s

# target to generate assembly for a file
scenes/textures.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/scenes/textures.cpp.s
.PHONY : scenes/textures.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... bomberman"
	@echo "... Animation.o"
	@echo "... Animation.i"
	@echo "... Animation.s"
	@echo "... app.o"
	@echo "... app.i"
	@echo "... app.s"
	@echo "... entities/Enemy.o"
	@echo "... entities/Enemy.i"
	@echo "... entities/Enemy.s"
	@echo "... entities/MovingEntities.o"
	@echo "... entities/MovingEntities.i"
	@echo "... entities/MovingEntities.s"
	@echo "... entities/Object.o"
	@echo "... entities/Object.i"
	@echo "... entities/Object.s"
	@echo "... entities/Player.o"
	@echo "... entities/Player.i"
	@echo "... entities/Player.s"
	@echo "... entities/Sprite.o"
	@echo "... entities/Sprite.i"
	@echo "... entities/Sprite.s"
	@echo "... entities/Text.o"
	@echo "... entities/Text.i"
	@echo "... entities/Text.s"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... scenes/GameOverScene.o"
	@echo "... scenes/GameOverScene.i"
	@echo "... scenes/GameOverScene.s"
	@echo "... scenes/GameScene.o"
	@echo "... scenes/GameScene.i"
	@echo "... scenes/GameScene.s"
	@echo "... scenes/MenuScene.o"
	@echo "... scenes/MenuScene.i"
	@echo "... scenes/MenuScene.s"
	@echo "... scenes/Scene.o"
	@echo "... scenes/Scene.i"
	@echo "... scenes/Scene.s"
	@echo "... scenes/WinScene.o"
	@echo "... scenes/WinScene.i"
	@echo "... scenes/WinScene.s"
	@echo "... scenes/textures.o"
	@echo "... scenes/textures.i"
	@echo "... scenes/textures.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

